# Generated by Django 2.2.1 on 2020-04-10 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('number', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('estimated_time', models.IntegerField(null=True)),
                ('is_repeated', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=100000)),
                ('token2', models.CharField(blank=True, max_length=1000000, null=True)),
                ('token3', models.CharField(blank=True, max_length=1000000, null=True)),
                ('block_code', models.IntegerField(blank=True, null=True)),
                ('last_try', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('api_endpoint', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('text', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('choice', 'choice'), ('range', 'range')], max_length=10, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='apiv1.Form')),
            ],
            options={
                'unique_together': {('text', 'form')},
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiv1.Question')),
                ('choice_type', models.CharField(choices=[('MA', 'multiple answer'), ('SA', 'single answer')], max_length=10)),
            ],
            bases=('apiv1.question',),
        ),
        migrations.CreateModel(
            name='RangeQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiv1.Question')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('start_text', models.CharField(blank=True, max_length=128, null=True)),
                ('end_text', models.CharField(blank=True, max_length=128, null=True)),
            ],
            bases=('apiv1.question',),
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apiv1.Question')),
            ],
            bases=('apiv1.question',),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=30)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='apiv1.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('picture', models.CharField(blank=True, max_length=1000000000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='apiv1.Profile'),
        ),
        migrations.CreateModel(
            name='AnsweredForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_form', to='apiv1.Form')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_form', to='apiv1.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoiceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='apiv1.Answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='apiv1.Choice')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answered_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='apiv1.AnsweredForm'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='apiv1.Question'),
        ),
        migrations.CreateModel(
            name='FormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('WIT', 'waiting')], default='WIT', max_length=128)),
                ('is_read', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_request', to='apiv1.Form')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_request', to='apiv1.Profile')),
            ],
            options={
                'unique_together': {('sender', 'form')},
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='apiv1.ChoiceQuestion'),
        ),
    ]
