# Generated by Django 2.2.1 on 2020-03-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_auto_20200308_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='end_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rangequestion',
            name='start_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
