# Generated by Django 2.2.1 on 2020-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20200308_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
        migrations.AddField(
            model_name='form',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='estimated_time',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
