# Generated by Django 2.2.1 on 2020-03-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_auto_20200309_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='is_repeaty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('sender', 'form')},
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='apiv1.Form')),
            ],
        ),
    ]
