# Generated by Django 2.2.1 on 2020-03-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_auto_20200309_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='is_repeaty',
            new_name='is_repeated',
        ),
        migrations.RemoveField(
            model_name='form',
            name='duration',
        ),
        migrations.AddField(
            model_name='form',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='estimated_time',
            field=models.IntegerField(null=True),
        ),
    ]
