# Generated by Django 2.2.1 on 2020-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_auto_20200309_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
