# Generated by Django 2.2.1 on 2020-03-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_auto_20200309_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='time',
            new_name='hour',
        ),
    ]
