# Generated by Django 2.2.1 on 2020-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0008_auto_20200309_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('number', 'form')},
        ),
    ]
