# Generated by Django 2.2.1 on 2020-03-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_auto_20200309_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACC', 'accepted'), ('REJ', 'rejected'), ('WIT', 'waiting')], default='WIT', max_length=128)),
                ('is_read', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_request', to='apiv1.Form')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_request', to='apiv1.Profile')),
            ],
            options={
                'unique_together': {('sender', 'form')},
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
