# Generated by Django 2.2.1 on 2020-03-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0011_form_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textquestion',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
