# Generated by Django 2.2.1 on 2020-03-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0012_auto_20200310_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='type',
            new_name='choice_type',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('choice', 'choice'), ('range', 'range')], max_length=10, null=True),
        ),
    ]
