# Generated by Django 2.2.1 on 2020-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0014_auto_20200310_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='hour',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'form')},
        ),
    ]
