# Generated by Django 2.2.1 on 2020-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0015_auto_20200407_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=15)),
                ('token', models.CharField(max_length=100000)),
                ('token2', models.CharField(blank=True, max_length=1000000, null=True)),
                ('token3', models.CharField(blank=True, max_length=1000000, null=True)),
                ('block_code', models.IntegerField(blank=True, null=True)),
                ('last_try', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.CharField(max_length=255)),
                ('api_endpoint', models.CharField(max_length=500)),
            ],
        ),
    ]
